
-- PROCEDIMIENTO ALAMACENADO PARA ELIMINAR USUARIO
DELIMITER //
CREATE PROCEDURE ELIMINAR_USUARIO(IN ID_USUARIO  BIGINT)
BEGIN
	START TRANSACTION;
	
	DELETE FROM tb_ventas WHERE idUsuario = ID_USUARIO;
	DELETE FROM tb_productos WHERE idUsuario = ID_USUARIO;
	DELETE FROM tb_usuario WHERE idUsuario = ID_USUARIO;

	COMMIT;
END //
DELIMITER;

CALL ELIMINAR_USUARIO(2)
-- ______________________________________________________