package com.dev_team.views;

import com.dev_team.models.Proveedor;
import com.dev_team.utilidades.GradientDialog;
import com.dev_team.utilidades.JButtonRound;
import com.dev_team.utilidades.Main_Colores;
import java.awt.Dimension;

public class D_AdmiComponentes extends GradientDialog {

    public D_AdmiComponentes(java.awt.Frame parent, boolean modal) {
        super(modal, Main_Colores.Fondo,Main_Colores.C_F800,Main_Colores.C_F700);
        initComponents();
        setSize(new Dimension(800, 550));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbx_componente = new javax.swing.JComboBox<>();
        btn_buscarC1 = new JButtonRound("Editar",30);
        btn_buscar = new JButtonRound("Guardar",30);
        tf_proveedor = new javax.swing.JTextField();
        tf_modelo = new javax.swing.JTextField();
        lb_3 = new javax.swing.JLabel();
        lb_4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_cantidad = new javax.swing.JTextField();
        lb_6 = new javax.swing.JLabel();
        tf_precio = new javax.swing.JTextField();
        lb_5 = new javax.swing.JLabel();
        lb_7 = new javax.swing.JLabel();
        tf_marca1 = new javax.swing.JTextField();
        tf_tamanio = new javax.swing.JTextField();
        tf_resolucion = new javax.swing.JTextField();
        tf_capacidad = new javax.swing.JTextField();
        tf_velocidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel13.setForeground(Main_Colores.C_100);
        jLabel13.setText("ADMINISTRAR COMPONENTES");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 360, 50));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setForeground(Main_Colores.C_100);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Componente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 200, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setForeground(Main_Colores.C_100);
        jLabel3.setText("Marca:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setForeground(Main_Colores.C_100);
        jLabel4.setText("Modelo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel7.setForeground(Main_Colores.C_100);
        jLabel7.setText("Componente:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 200, 160));

        cbx_componente.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cbx_componente.setForeground(Main_Colores.Fondo);
        cbx_componente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion:" }));
        getContentPane().add(cbx_componente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 210, 30));

        btn_buscarC1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btn_buscarC1.setForeground(Main_Colores.Fondo);
        btn_buscarC1.setText("Editar");
        btn_buscarC1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btn_buscarC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 130, -1));

        btn_buscar.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btn_buscar.setForeground(Main_Colores.Fondo);
        btn_buscar.setText("Guardar");
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 130, 30));

        tf_proveedor.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tf_proveedor.setForeground(Main_Colores.Fondo);
        getContentPane().add(tf_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 180, -1));

        tf_modelo.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tf_modelo.setForeground(Main_Colores.Fondo);
        getContentPane().add(tf_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 180, -1));

        lb_3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lb_3.setForeground(Main_Colores.C_100);
        lb_3.setText("Capacidad:");
        getContentPane().add(lb_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        lb_4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lb_4.setForeground(Main_Colores.C_100);
        lb_4.setText("Velocidad:");
        getContentPane().add(lb_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel8.setForeground(Main_Colores.C_100);
        jLabel8.setText("Proveedor:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel14.setForeground(Main_Colores.C_100);
        jLabel14.setText("Cantidad:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        tf_cantidad.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tf_cantidad.setForeground(Main_Colores.Fondo);
        getContentPane().add(tf_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 130, 30));

        lb_6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lb_6.setForeground(Main_Colores.C_100);
        lb_6.setText("Precio:");
        getContentPane().add(lb_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        tf_precio.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tf_precio.setForeground(Main_Colores.Fondo);
        getContentPane().add(tf_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 140, 30));

        lb_5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lb_5.setForeground(Main_Colores.C_100);
        lb_5.setText("Tamaño:");
        getContentPane().add(lb_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lb_7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lb_7.setForeground(Main_Colores.C_100);
        lb_7.setText("Resolucion:");
        getContentPane().add(lb_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, 20));

        tf_marca1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tf_marca1.setForeground(Main_Colores.Fondo);
        getContentPane().add(tf_marca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 180, -1));

        tf_tamanio.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tf_tamanio.setForeground(Main_Colores.Fondo);
        getContentPane().add(tf_tamanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, -1));

        tf_resolucion.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tf_resolucion.setForeground(Main_Colores.Fondo);
        getContentPane().add(tf_resolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 180, -1));

        tf_capacidad.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tf_capacidad.setForeground(Main_Colores.Fondo);
        getContentPane().add(tf_capacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 180, -1));

        tf_velocidad.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tf_velocidad.setForeground(Main_Colores.Fondo);
        getContentPane().add(tf_velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_AdmiComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_AdmiComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_AdmiComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_AdmiComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                D_AdmiComponentes dialog = new D_AdmiComponentes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_buscarC1;
    private javax.swing.JComboBox<String> cbx_componente;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    protected javax.swing.JLabel lb_3;
    protected javax.swing.JLabel lb_4;
    protected javax.swing.JLabel lb_5;
    protected javax.swing.JLabel lb_6;
    protected javax.swing.JLabel lb_7;
    protected javax.swing.JTextField tf_cantidad;
    private javax.swing.JTextField tf_capacidad;
    private javax.swing.JTextField tf_marca1;
    private javax.swing.JTextField tf_modelo;
    protected javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_proveedor;
    private javax.swing.JTextField tf_resolucion;
    private javax.swing.JTextField tf_tamanio;
    private javax.swing.JTextField tf_velocidad;
    // End of variables declaration//GEN-END:variables
}
