/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dev_team.views;

import com.dev_team.utilidades.Main_Colores;

/**
 *
 * @author DevMaik
 */
public class V_RegistrarProducto extends javax.swing.JPanel {

    /**
     * Creates new form V_RegistrarProducto
     */
    public V_RegistrarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_precioUnitario = new javax.swing.JTextField();
        tf_cantidad = new javax.swing.JTextField();
        tf_precioTotal = new javax.swing.JTextField();
        cbx_categoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbx_clave = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel19.setForeground(Main_Colores.C_100);
        jLabel19.setText("Precio total:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 130, -1));

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel16.setForeground(Main_Colores.C_100);
        jLabel16.setText("Precio unitario:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 130, -1));

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel18.setForeground(Main_Colores.C_100);
        jLabel18.setText("Cantidad:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        tf_precioUnitario.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        tf_precioUnitario.setForeground(Main_Colores.Fondo);
        add(tf_precioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 150, 30));

        tf_cantidad.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        tf_cantidad.setForeground(Main_Colores.Fondo);
        add(tf_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 150, 30));

        tf_precioTotal.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tf_precioTotal.setForeground(Main_Colores.Fondo);
        tf_precioTotal.setEnabled(false);
        add(tf_precioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 140, 30));

        cbx_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE CATEGORIA", "Computadora", "Laptop", "Componente", "Accesorio" }));
        add(cbx_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 170, 30));

        jLabel1.setText("Categorias");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel2.setText("Clave Producto");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        add(cbx_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 180, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JComboBox<String> cbx_categoria;
    protected javax.swing.JComboBox<String> cbx_clave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    protected javax.swing.JTextField tf_cantidad;
    protected javax.swing.JTextField tf_precioTotal;
    protected javax.swing.JTextField tf_precioUnitario;
    // End of variables declaration//GEN-END:variables
}
