/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dev_team.views;

import com.dev_team.utilidades.JButtonRound;
import com.dev_team.utilidades.Main_Colores;
import com.dev_team.utilidades.PanelGradient;
import com.dev_team.utilidades.Panel_Round;
import java.awt.Color;
import org.jdesktop.swingx.JXList;

/**
 *
 * @author DevMaik
 */
public class V_Ventas extends javax.swing.JPanel {

    /**
     * Creates new form V_Ventas
     */
    public V_Ventas() {
        initComponents();

        panel_main.setBackground(Main_Colores.Fondo);
        setBackground(Main_Colores.Fondo_2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new Panel_Round(20,Color.CYAN,Color.BLUE);
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_productos = new org.jdesktop.swingx.JXTable();
        tf_total = new javax.swing.JTextField();
        tf_cantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_id_producto = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        btn_vender = new JButtonRound("Vender",20);
        tf_descuento = new javax.swing.JTextField();
        cbx_metodo = new javax.swing.JComboBox<>();
        panel_cliente = new PanelGradient(Color.WHITE,Main_Colores.C_300);
        sh_buscarCliente = new org.jdesktop.swingx.JXSearchField();
        tf_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        tf_telefono = new javax.swing.JTextField();
        btn_limpiar = new JButtonRound("Limpiar",20);
        jPanel2 = new PanelGradient(Color.MAGENTA,Color.RED);
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(Main_Colores.Fondo_2);

        panel_main.setBackground(new java.awt.Color(255, 255, 255));
        panel_main.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(Main_Colores.Fondo);
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 40));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_productos.setColumnControlVisible(true);
        tb_productos.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(tb_productos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 570, 290));

        tf_total.setBackground(Main_Colores.C_100);
        tf_total.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tf_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_totalActionPerformed(evt);
            }
        });
        jPanel3.add(tf_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, 110, 30));

        tf_cantidad.setBackground(Main_Colores.C_100);
        tf_cantidad.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel3.add(tf_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 110, 30));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setForeground(Main_Colores.C_100);
        jLabel1.setText("ID Producto:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setForeground(Main_Colores.C_100);
        jLabel2.setText("Cantidad:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setForeground(Main_Colores.C_100);
        jLabel3.setText("Descuento: %");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel9.setForeground(Main_Colores.C_100);
        jLabel9.setText("Precio:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel10.setForeground(Main_Colores.C_100);
        jLabel10.setText("Total:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, -1, -1));

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel11.setForeground(Main_Colores.C_100);
        jLabel11.setText("Metodo Pago:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, -1, -1));

        tf_id_producto.setBackground(Main_Colores.C_100);
        tf_id_producto.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel3.add(tf_id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 100, 30));

        tf_precio.setBackground(Main_Colores.C_100);
        tf_precio.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel3.add(tf_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 100, 30));

        btn_vender.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btn_vender.setForeground(new java.awt.Color(0, 0, 0));
        btn_vender.setText("Vender");
        btn_vender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btn_vender, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 610, 90, 40));

        tf_descuento.setBackground(Main_Colores.C_100);
        tf_descuento.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel3.add(tf_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 100, 30));

        cbx_metodo.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cbx_metodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));
        jPanel3.add(cbx_metodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, 110, 30));

        panel_cliente.setBackground(Color.WHITE
        );
        panel_cliente.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        panel_cliente.setMinimumSize(new java.awt.Dimension(150, 80));
        panel_cliente.setPreferredSize(new java.awt.Dimension(250, 200));
        panel_cliente.setLayout(new org.jdesktop.swingx.VerticalLayout());

        sh_buscarCliente.setBackground(new java.awt.Color(255, 255, 255));
        sh_buscarCliente.setBorder(null);
        sh_buscarCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sh_buscarCliente.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        sh_buscarCliente.setMargin(new java.awt.Insets(10, 6, 2, 6));
        sh_buscarCliente.setMaximumSize(new java.awt.Dimension(200, 400));
        sh_buscarCliente.setPreferredSize(new java.awt.Dimension(200, 40));
        sh_buscarCliente.setPrompt("Buscar Cliente");
        sh_buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sh_buscarClienteActionPerformed(evt);
            }
        });
        panel_cliente.add(sh_buscarCliente);

        jPanel3.add(panel_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 190, 630));

        tf_nombre.setBackground(Main_Colores.C_100);
        tf_nombre.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel3.add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 200, 30));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel5.setForeground(Main_Colores.C_100);
        jLabel5.setText("Nombre:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        tf_apellido.setBackground(Main_Colores.C_100);
        tf_apellido.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel3.add(tf_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 200, 30));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel6.setForeground(Main_Colores.C_100);
        jLabel6.setText("Apellido:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel7.setForeground(Main_Colores.C_100);
        jLabel7.setText("Email:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel8.setForeground(Main_Colores.C_100);
        jLabel8.setText("telefono");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        tf_email.setBackground(Main_Colores.C_100);
        tf_email.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel3.add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 230, 30));

        tf_telefono.setBackground(Main_Colores.C_100);
        tf_telefono.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel3.add(tf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 230, 30));

        btn_limpiar.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btn_limpiar.setForeground(new java.awt.Color(0, 0, 0));
        btn_limpiar.setText("Limpiar");
        btn_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 100, 40));

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 170));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 160));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        jLabel12.setForeground(Main_Colores.C_100);
        jLabel12.setText("VENTAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(jLabel12)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 50));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel4.setForeground(Main_Colores.C_100);
        jLabel4.setText("DATOS CLIENTE");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 180, 40));

        panel_main.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(panel_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(panel_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sh_buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sh_buscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sh_buscarClienteActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        tf_apellido.setText("");
        tf_nombre.setText("");
        tf_telefono.setText("");
        tf_email.setText("");
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void tf_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_totalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_limpiar;
    protected javax.swing.JButton btn_vender;
    protected javax.swing.JComboBox<String> cbx_metodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JPanel panel_cliente;
    private javax.swing.JPanel panel_main;
    protected org.jdesktop.swingx.JXSearchField sh_buscarCliente;
    protected org.jdesktop.swingx.JXTable tb_productos;
    protected javax.swing.JTextField tf_apellido;
    protected javax.swing.JTextField tf_cantidad;
    protected javax.swing.JTextField tf_descuento;
    protected javax.swing.JTextField tf_email;
    protected javax.swing.JTextField tf_id_producto;
    protected javax.swing.JTextField tf_nombre;
    protected javax.swing.JTextField tf_precio;
    protected javax.swing.JTextField tf_telefono;
    protected javax.swing.JTextField tf_total;
    // End of variables declaration//GEN-END:variables
}
