/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dev_team.views;

import org.jdesktop.swingx.JXList;


/**
 *
 * @author DevMaik
 */
public class V_Ventas extends javax.swing.JPanel {

    /**
     * Creates new form V_Ventas
     */
    public V_Ventas() {
        initComponents();
        
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_apellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_telefono = new javax.swing.JTextField();
        btn_limpiar = new javax.swing.JButton();
        panel_cliente = new javax.swing.JPanel();
        sh_buscarCliente = new org.jdesktop.swingx.JXSearchField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_productos = new org.jdesktop.swingx.JXTable();
        tf_total = new javax.swing.JTextField();
        tf_cantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_id_producto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_precio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tf_descuento = new javax.swing.JTextField();
        cbx_metodo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 170));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 160));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("DATOS CLIENTE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));
        jPanel2.add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 280, 40));

        jLabel5.setText("Nombre:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jLabel6.setText("Apellido:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));
        jPanel2.add(tf_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 240, 40));

        jLabel7.setText("Email:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));
        jPanel2.add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 280, 40));

        jLabel8.setText("telefono");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));
        jPanel2.add(tf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 240, 40));

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 100, 40));

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        panel_cliente.setMinimumSize(new java.awt.Dimension(150, 80));
        panel_cliente.setPreferredSize(new java.awt.Dimension(250, 200));
        org.jdesktop.swingx.VerticalLayout verticalLayout1 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout1.setGap(10);
        panel_cliente.setLayout(verticalLayout1);

        sh_buscarCliente.setBackground(new java.awt.Color(255, 255, 255));
        sh_buscarCliente.setBorder(null);
        sh_buscarCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sh_buscarCliente.setMargin(new java.awt.Insets(10, 6, 2, 6));
        sh_buscarCliente.setMaximumSize(new java.awt.Dimension(200, 400));
        sh_buscarCliente.setPreferredSize(new java.awt.Dimension(200, 40));
        sh_buscarCliente.setPrompt("Buscar Cliente");
        sh_buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sh_buscarClienteActionPerformed(evt);
            }
        });
        panel_cliente.add(sh_buscarCliente);

        jPanel1.add(panel_cliente, java.awt.BorderLayout.WEST);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 40));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_productos.setColumnControlVisible(true);
        jScrollPane1.setViewportView(tb_productos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 690, 310));
        jPanel3.add(tf_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 110, 40));
        jPanel3.add(tf_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 110, 40));

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Cantidad:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("ID Producto");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));
        jPanel3.add(tf_id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 90, 40));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Descuento: %");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));
        jPanel3.add(tf_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 90, 44));

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Precio");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jButton1.setText("Vender");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 110, 60));

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Total");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));
        jPanel3.add(tf_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 100, 40));

        cbx_metodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));
        jPanel3.add(cbx_metodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 120, 40));

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Metodo Pago");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void sh_buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sh_buscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sh_buscarClienteActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        tf_apellido.setText("");
        tf_nombre.setText("");
        tf_telefono.setText("");
        tf_email.setText("");
    }//GEN-LAST:event_btn_limpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_limpiar;
    protected javax.swing.JComboBox<String> cbx_metodo;
    protected javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JPanel panel_cliente;
    protected org.jdesktop.swingx.JXSearchField sh_buscarCliente;
    protected org.jdesktop.swingx.JXTable tb_productos;
    protected javax.swing.JTextField tf_apellido;
    protected javax.swing.JTextField tf_cantidad;
    protected javax.swing.JTextField tf_descuento;
    protected javax.swing.JTextField tf_email;
    protected javax.swing.JTextField tf_id_producto;
    protected javax.swing.JTextField tf_nombre;
    protected javax.swing.JTextField tf_precio;
    protected javax.swing.JTextField tf_telefono;
    protected javax.swing.JTextField tf_total;
    // End of variables declaration//GEN-END:variables
}
